name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    strategy:
      matrix:
        typst-version: ["0.13"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Probe runner package cache
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: cargo
          version: 1.0

      - name: Setup typst
        uses: typst-community/setup-typst@v3
        with:
          typst-version: ${{ matrix.typst-version }}

      - name: Install tytanic from crates.io
        uses: baptiste0928/cargo-install@v3.0.0
        with:
          crate: tytanic
          version: '0.2.1'

      - name: Run test suite
        run: tt run --no-fail-fast

      - name: Archive diffs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: diffs
          path: |
            tests/**/diff/*.png
            tests/**/out/*.png
          retention-days: 5